#!/bin/bash
. "/usr/local/bin/config"

all_good=1

if [ $(ps -ef | grep "plexdrive" | grep -v "grep" | wc -l) -gt "0" ]; then
    printf "\n\nPlexdrive is not running\n\n"
    all_good=0
fi

if [ $(ps -ef | grep "rclone" | grep -v "grep" | wc -l) -gt "0" ]; then
    printf "\n\nRclone is not running\n\n"
    all_good=0
fi

if [ $(ps -ef | grep "unionfs" | grep -v "grep" | wc -l) -gt "0" ]; then
    printf "\n\nUnionFS is not running\n\n"
    all_good=0
fi

if [ "$all_good" -eq "1" ]; then
   printf "\n\nEverything looks good\n\n"
   exit 02
fi