#!/bin/bash
. "/usr/bin/config"

all_good=1

check_rclone_cloud
check_rclone_local

if [ $(ps -ef | grep "mongod" | grep -v "grep" | wc -l) == "0" ]; then
    printf "\n\nMongoDB is not running\n\n"
    all_good=0
fi

if [ $(ps -ef | grep "plexdrive" | grep -v "grep" | wc -l) == "0" ]; then
    printf "\n\nPlexdrive is not running\n\n"
    all_good=0
fi

if [ "$(printenv ENCRYPT_MEDIA)" != "0" ]; then
    if [ -z "$(ls -A ${cloud_encrypt_dir})" ]; then
        printf "\n\nWaiting for ${cloud_encrypt_dir}\n\n"
        exit 0
    fi

    if [ $(ps -ef | grep "rclone" | grep -v "grep" | wc -l) == "0" ]; then
        printf "\n\nRclone is not running\n\n"
        all_good=0
    fi
fi

if [ -z "$(ls -A ${cloud_decrypt_dir})" ]; then
    printf "\n\nWaiting for ${cloud_encrypt_dir}\n\n"
    exit 0
fi

if [ $(ps -ef | grep "unionfs" | grep -v "grep" | wc -l) == "0" ]; then
    printf "\n\nUnionFS is not running\n\n"
    all_good=0
fi

if [ "$all_good" -eq "1" ]; then
   printf "\n\nEverything looks good\n\n"
   exit 0
fi