#!/bin/bash
. "/usr/local/bin/variables"

echo "Starting MongoDB"
mongod --fork --logpath "${log_dir}/mongod.log"
echo "MongoDB started"

echo "Mounting..."
mount
echo "Mounted"

while /bin/true; do
  sleep 60
done