#!/bin/bash

. "/usr/local/bin/variables"

echo "\n\n\n=============================================================="

echo "Setup Plexdrive"

echo "==============================================================\n\n\n"

plexdrive $mongo $plexdrive_options "${cloud_encrypt_dir}"