#!/bin/sh

mongo="--mongo-database=plexdrive --mongo-host=localhost --mongo-user=admin --mongo-password=plexdrive"
plexdrive_options="--temp=${plexdrive_temp_dir} -o allow_other --clear-chunk-max-size$(printenv CLEAR_CHUNK_MAX_SIZE) --chunk-size=$(printenv CHUNK_SIZE)"

plexdrive --config="/config" $mongo $plexdrive_options "${cloud_encrypt_dir}"