#!/bin/bash

. "/usr/local/bin/variables"

printf "\n\n\n==============================================================\n"

echo "Setup Plexdrive"

printf "==============================================================\n\n\n"

plexdrive $mongo $plexdrive_options "${cloud_encrypt_dir}"