#!/bin/sh
. "/usr/local/bin/variables"

echo "Setup following endpoints in rclone:"
echo " - Endpoint to your cloud storage"
echo " - $(printenv RCLONE_CLOUD_ENDPOINT) connected to your cloud storage"
echo " - $(printenv RCLONE_LOCAL_ENDPOINT) connected to your local storage"

/bin/bash -c rclone config $rclone_options