#!/bin/sh
. "/usr/local/bin/variables"

echo "\n\n\n=============================================================="

echo "Setup following endpoints in rclone:"
echo " - Endpoint to your cloud storage"
echo " - $(printenv RCLONE_CLOUD_ENDPOINT) connected to your cloud storage"
echo " - $(printenv RCLONE_LOCAL_ENDPOINT) connected to your local storage"

echo "==============================================================\n\n\n"

rclone $rclone_config config