#!/bin/bash
. "/usr/local/bin/variables"

printf "\n\n\n==============================================================\n"

echo "Setup following endpoints in rclone:"
echo " - Endpoint to your cloud storage"
echo " - $(printenv RCLONE_CLOUD_ENDPOINT) connected to your cloud storage"
echo " - $(printenv RCLONE_LOCAL_ENDPOINT) connected to your local storage"

printf "==============================================================\n\n\n"

rclone $rclone_config config